### ISSUE TITLE
Reproducibility of edge probing tasks

### ISSUE THREAD

**Issue by sagnik** [nyu-mll/jiant#1305]
**Describe the bug**
I am having a bit of trouble reproducing the results for edge probing tasks. Various people seemed to have reported various results. For simplicity, I will use the example for Coref on ontonotes data, and the ones that use the top layer of BERT. 

1. [Tenney 2019, ICLR](https://arxiv.org/abs/1905.06316):  bert-base-uncased, 90.2. I don't quite understand the `cat` part.
2. [Tenney 2019, Bert rediscovers](https://arxiv.org/abs/1905.05950): bert-base-large, 91.9.
3. [Van aken 2019](https://arxiv.org/abs/1909.04925): bert-base-uncased, approx 95, figure 2.
4. [Merchant 2020](https://arxiv.org/abs/1909.04925): bert-base-uncased, 95.2, appendix, table 2.
5. When I run using the existing Jiant, w/o any code change (I have made some changes in the code to read yml files): bert-base-uncased, 92.6 (average over 5 runs).

```
jiant_task_container_config_path: ${JIANT_HOME}/run_configs/coref_bert_run_config.yml
output_dir: ${JIANT_DATA}/runs/coref_bert_es
hf_pretrained_model_name_or_path: bert-base-uncased
model_path: ${JIANT_DATA}/models/bert-base-uncased/model/model.p
model_config_path: ${JIANT_DATA}/models/bert-base-uncased/model/config.json
learning_rate: 0.00001
eval_every_steps: 500
no_improvements_for_n_evals: 100
do_train: true
do_val: true
do_save: true
write_val_preds: true
write_test_preds: true
force_overwrite: true
```

Where coref_bert_run_config is given by 
```
task_config_path_dict:
  coref: ${JIANT_HOME}/tasks/configs/coref_config.yml
task_cache_config_dict:
  coref:
    train: ${JIANT_DATA}/cache/coref/train
    val: ${JIANT_DATA}/cache/coref/val
    val_labels: ${JIANT_DATA}/cache/coref/val_labels
    test: ${JIANT_DATA}/cache/coref/test
    test_labels: ${JIANT_DATA}/cache/coref/test_labels
sampler_config:
  sampler_type: ProportionalMultiTaskSampler
global_train_config:
  max_steps: 129900
  warmup_steps: 12990
task_specific_configs_dict:
  coref:
    train_batch_size: 16
    eval_batch_size: 8
    gradient_accumulation_steps: 1
    eval_subset_num: 500
taskmodels_config:
  task_to_taskmodel_map:
    coref: coref
  taskmodel_config_map:
    coref: null
task_run_config:
  train_task_list: &id001
  - coref
  train_val_task_list: *id001
  val_task_list:
  - coref
  test_task_list:
  - coref
metric_aggregator_config:
  metric_aggregator_type: EqualMetricAggregator
```
However, I am also wondering where is the encoder frozen in the existing implementation, which I think is necessary, right? As [Tenney 2019, Bert rediscovers](https://arxiv.org/abs/1905.05950) writes, 
![image](https://user-images.githubusercontent.com/4563472/113227710-52965900-9261-11eb-9263-869302dabab6.png)
If I look back in the original implementation branch for Tenney papers, there is an option to [do this](https://github.com/nyu-mll/jiant/blob/ead63af002e0f755c6418478ec3cabb4062a601e/jiant/bert/utils.py#L61), which I can not find in the existing code. If I freeze the encoder weights myself just by doing encoder, the result for Coref reduces down to 77.7 for bert-base-uncased, which is really low but corresponds well to [Liu 2019](https://www.aclweb.org/anthology/N19-1112/) paper, appendix D6 (the data is the same AFAICT, but there is no self-attention pooling layer over the spans). Given this, my question is: where is the encoder frozen for EP tasks? Or am I understanding the task design completely wrong?     

Here's the original code for multi label span classification in the existing implementation:

```
    elif task.TASK_TYPE == TaskTypes.MULTI_LABEL_SPAN_CLASSIFICATION:
        assert taskmodel_kwargs is None
        span_comparison_head = heads.SpanComparisonHead(
            hidden_size=hidden_size,
            hidden_dropout_prob=hidden_dropout_prob,
            num_spans=task.num_spans,
            num_labels=len(task.LABELS),
        )
        taskmodel = taskmodels.MultiLabelSpanComparisonModel(
            encoder=encoder, span_comparison_head=span_comparison_head,
        )
```

```
class MultiLabelSpanComparisonModel(Taskmodel):
    def __init__(self, encoder, span_comparison_head: heads.SpanComparisonHead):
        super().__init__(encoder=encoder)
        self.span_comparison_head = span_comparison_head

    def forward(self, batch, task, tokenizer, compute_loss: bool = False):
        encoder_output = get_output_from_encoder_and_batch(encoder=self.encoder, batch=batch)
        logits = self.span_comparison_head(unpooled=encoder_output.unpooled, spans=batch.spans)
        if compute_loss:
            loss_fct = nn.BCEWithLogitsLoss()
            loss = loss_fct(
                logits.view(-1, self.span_comparison_head.num_labels), batch.label_ids.float(),
            )
            return LogitsAndLossOutput(logits=logits, loss=loss, other=encoder_output.other)
        else:
            return LogitsOutput(logits=logits, other=encoder_output.other)
```

I added this before creating taskmodel:
```
for param in encoder.parameters():
            param.requires_grad = False
```			

**To Reproduce**
1. Tell use which version of `jiant` you're using: the latest one, with some modifications for reading yml files.
2. Describe the environment where you're using `jiant`, e.g, "2 P40 GPUs": single nvidia GPU
3. Provide the experiment config artifact (e.g., `defaults.conf`): see above.

**Expected behavior**

**Screenshots**

**Additional context**
